### ISSUE TITLE
[Announcement] Homework 2 is out (Updated: 3/12)

### ISSUE THREAD

**Issue by yeonhee-ryou** [prosyslab-classroom/is661-advanced-software-security#36]
Hi, everyone.

This is the announcement for Homework 2.
Read the instruction [HW2: Your quick sort paper](https://github.com/prosyslab-classroom/is661-advanced-software-security/blob/main/quicksort.md) and write a paper.

Here is the GitHub classroom link for this homework:
https://classroom.github.com/a/6Uoc2spX

You MUST submit both:
- commit & push your **tex & pdf files** to your homework repository,
- and submit your **pdf file** to the HotCRP.

Use the "New HW2 submission" button on the HotCRP.
![image](https://github.com/prosyslab-classroom/is661-advanced-software-security/assets/17640199/d56ab62f-7eeb-42e1-8911-caf73da0636f)

Don't assign any conflict.

## Syntactic Requirements (Different from the template README.md)
- You can write more than 2 pages, but only **up to 5 pages**. More pages for references (bib) are permitted.
- Write your paper in the structure of general technical papers including abstract, introduction, etc.
- Write in English (한국인 학생들도 영어로 작성하세요). Your paper will be reviewed by other students (HW3).

## Due date
Due: ~3. 12 (Tue.) 23:59:59~ --> 3. 13 (Wed.) 05:59:59

**Comment by KihongHeo** [comment]
If you need experimental data, it is okay to use arbitrary data and numbers for this assignment.
